### ISSUE TITLE
Icons on the homepage fail to load when not using https

### ISSUE THREAD

**Issue by jacobcoughenour** [theumod/umod.org#36]
Here's the error from chrome
`(index):1 Access to Font at 'https://umod.org/assets/fonts/pe-icon-7-stroke.woff?d7yf1v' from origin 'http://umod.org' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header has a value 'https://forums.umod.org' that is not equal to the supplied origin. Origin 'http://umod.org' is therefore not allowed access.`

**Comment by lukespragg** [comment]
SSL is forced now, so this likely won't be an issue anymore.
